### PR TITLE
Jan Fixes and Enhancements

### LINKED ISSUE #462: [BUG] Firefox hangs on the start mapping page
**Describe the bug**
The start mapping page hangs while making prediction on the start mapping page.

**To Reproduce**
Watch the attached video here https://github.com/hotosm/fAIr/pull/461#issuecomment-3568239226:

**Expected behavior**
Everything should work fine.

**Desktop (please complete the following information):**
 - Browser : Firefox

### PR DESCRIPTION
**Pull request by jeafreezy**
### What does this PR do ?

This PR includs some features and bugs raised on Slack.

1. [x] Added zoom controls to offline predictions results map.
2. [x] Updated mapswipe results button text.
3. [x] Added refresh button to check mapswipe status.
4. [x] Activated learn and resources page.
5. [x] Reduced OSM basemap maxzoom to zoom 19 and increased tilesize to 256 to prevent unnecessary requests (this somehow happen to fix #462)
6. [x] Fixed bug with stale dataset in training area page (sometimes when you visit the training area twice, it renders the previous training dataset imagery.)
7. [x] Fixed validation bug in model enhancement modal.
8. [x] Fixed bug in stale state when reopening traning enhancement settings modal.
9. [x] Fixed validation bug in training settings page.
10. [x] Learn page with the video carousel and share functionality.

### Screenshots

1.
https://github.com/user-attachments/assets/9a52e292-adee-45f1-bcdb-13deca5830b7

2.
Screenshot 2026-01-18 at 21 06 14

3.
https://github.com/user-attachments/assets/0b50a75d-ab86-49e0-bd9a-c93a17b76a53

4.
https://github.com/user-attachments/assets/1d3727b2-3ab0-4a01-9c56-3019b737f3cc

5.

**Before - Lots's of CORS error because OSM does not provide tiles at zoom 20+.**

https://github.com/user-attachments/assets/37e6b677-8c3f-418e-952c-1865c65fc172

**After - Making maxzoom to be 19 prevents this from happening.**

https://github.com/user-attachments/assets/96a41bc7-ffd0-45cc-826d-605888ac6637

6.

**Before (currently in prod/dev)**

https://github.com/user-attachments/assets/f58b56a8-7d29-4254-a9d9-eda954657e8c

**After** 

https://github.com/user-attachments/assets/27408dce-8317-4589-96bb-468ee992198a

7.

**Before**

https://github.com/user-attachments/assets/632f0557-2018-4e2a-93d9-24f8589b2760

**After**

https://github.com/user-attachments/assets/4d1bcf40-cc68-4236-af85-f453cbb4a6e2

8.

**Before**

https://github.com/user-attachments/assets/7ba1cdab-f3da-4970-b870-5b22432880f5

**After**

https://github.com/user-attachments/assets/116afef3-4e94-4ec0-8ba7-99fadea199a3

9.

**Before**

https://github.com/user-attachments/assets/2b495ad8-fc87-45d2-bdb5-87aa5b343135

**After**

https://github.com/user-attachments/assets/456825a3-f86e-4891-87d8-4efd50c5a3a4

10.

https://github.com/user-attachments/assets/bdd262ce-3930-4b13-8f88-5a881e25b682

### How to Test

https://fair-dev-spatialnode.vercel.app/

### CODE REVIEW

**Comment by kshitijrajsharma** [comment]
image
There are still lot of history API calls in the start mapping page , it is bombbarding browser within short period of time , is there a way to control it ?

**Review by kshitijrajsharma — CHANGES_REQUESTED** [review]
I couldn't verify the bug fixes, one more iteration would be needed

File: frontend/src/utils/regex-utils.ts [hunk 1]
```diff
@@ -41,7 +41,20 @@ export const getTileServerRegex = (serviceType: TileServiceType) => {
...
+ * Function to extract the YouTube video ID from a given URL.
+ * This function matches common YouTube URL formats such as watch, embed, and short links.
+ *
+ * @param url - The YouTube URL to parse.
+ * @returns The extracted 11-character YouTube video ID, or null if no match is found.
+ */
+export const extractYouTubeVideoId = (url: string): string | null => {
+  // Regex to match various YouTube URL formats
+  const youtubeRegex =
+    /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/|v\/)|youtu\.be\/)([\w-]{11})/i;
```
Comment (kshitijrajsharma) [inline frontend/src/utils/regex-utils.ts:54]: This seems problematic !
