### PR TITLE
February Fixes and Enhancements

### LINKED ISSUE #468: Feat : add chloropleth map on aggreement for mapswipe results
Image

Map on frontend should look like this based on the properties agreement  it should be chloropleth map based on the value of agreement 

Image

### PR DESCRIPTION
**Pull request by jeafreezy**
### What does this PR do ?

This PR includes the following minor enhancements and bug fixes:

1. Brought back to cursor instruction on the start mapping page.
2. Persist the update slug to the url when the modal is opened on the learn page.
3. Fix minor alignment on the copy button on the training logs modal.
4. Made the tooltip text on the share icon on the learn page video card a bit more descriptive.
5. Removed `.toLowerCase()` in MapSwipe project topic. This ensures all created projects retains the case without enforcing lowercase.
6. Made MapSwipe `verification number` default to `4` and also made it and `groupSize` configurable environment variables.
7. Implemented choropleth to visualize MapSwipe agreement + Legend. Closes #468 
8. Hamburger menu fix on mobile.
9. Pre commit hook setup.
10. Updated default model settings with new values.
11. Updated button text when uploading training area to be more clear.

### Screenshots

1.

**Before**

https://github.com/user-attachments/assets/8bf0e5a0-3c4e-4a2e-bb84-86a14ee47b9d

**After**

https://github.com/user-attachments/assets/240e8b68-cd65-4899-abdd-de6f6bebdbbc

2.

**Before**

https://github.com/user-attachments/assets/a539d703-4783-4696-a527-9992f29e4feb

**After**

https://github.com/user-attachments/assets/3751043f-3428-4e97-bdb0-3473aa00ec38

3.

**Before**

https://github.com/user-attachments/assets/add60795-8135-43fd-84b1-bd950815b888

**After**

https://github.com/user-attachments/assets/20114288-69fc-48ec-aee7-9b491b99d116

4.

**Before**

https://github.com/user-attachments/assets/578574c2-222c-467c-a4c2-a24b8d903e87

**After**

https://github.com/user-attachments/assets/619dbc0b-ef05-4b1d-b1c9-921af7f80225

5.

**Before**

https://github.com/user-attachments/assets/59611aab-bbf6-4c6d-a3ec-b214945bb2ec

**After**

https://github.com/user-attachments/assets/df09fea8-9f6b-4c71-9bb2-8a82e4144e02

6.

**Before**

https://github.com/user-attachments/assets/e4b5d079-fc6e-4fb9-a263-becf74bc4e6c

**After**

https://github.com/user-attachments/assets/dee0cf9d-6d75-4fa9-87bf-b312aec99758

7.

**Before**

https://github.com/user-attachments/assets/d188446e-01bf-48f9-a262-6c0f99c78ac4

**After**

https://github.com/user-attachments/assets/5c79a6f4-3c2b-48ab-bcea-d50f177360c0

8. 

**Before**

https://github.com/user-attachments/assets/1040d52a-4037-4d99-b5f5-811b0cada40b

**After**

https://github.com/user-attachments/assets/1f9e082d-fbe2-4710-b31e-7e621efc93f8

### How to Test

[fair-dev-spatialnode.vercel.app](https://fair-dev-spatialnode.vercel.app/)

### CODE REVIEW

File: frontend/src/config/env.ts [hunk 1]
```diff
@@ -98,4 +98,6 @@ export const ENVS = {
 
   FAIR_YOUTUBE_UPDATES_URL: import.meta.env.FAIR_VIDEO_UPDATES_URL,
   FAIR_VIDEO_BACKUP_URL: import.meta.env.FAIR_VIDEO_BACKUP_URL,
+  MAPSWIPE_VERIFICATION_NUMBER: import.meta.env.VITE_MAPSWIPE_VERIFICATION_NUMBER,
```
Comment (kshitijrajsharma) [inline frontend/src/config/env.ts]: Nice !

**Review by kshitijrajsharma — COMMENTED** [review]
I think we would also need legend in the map to show what color represents ?

**Comment by jeafreezy** [comment]
> I think we would also need legend in the map to show what color represents ?

Yes, it’s coming: https://github.com/Spatialnode/fAIr/pull/9

Converted this to draft. Will reopen for your review when it’s merged.

Thanks

**Review by kshitijrajsharma — APPROVED** [review]
